# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine
ARG jarname
# copy application WAR (with libraries inside)

RUN mkdir /app

WORKDIR /app

# specify default command
CMD ["/usr/bin/java", "-jar", "/app/$jarname"]
